sudo: required
language: bash

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=piotrovskyi/protractor-headless
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$COMMIT .

after_success:
  - docker tag $REPO:$COMMIT $REPO:beta-$TAG
  - docker push $REPO:beta-$TAG
